repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-toml
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.277
    hooks:
    -   id: ruff
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black